nsq:
  - nsqd-addrs:
    - 127.0.0.1:4150
    # - 192.168.33.10:4150
  - nsqlookupd-addrs:
    - 127.0.0.1:4160
    # - 192.168.33.10:4160
  - channels:
    - email-chan
    # - sms-chan
  - topics:
    - invite-friend
    # - send-
  - logdir:
    - /tmp
